name: front
description: A new Flutter project.

publish_to: 'none' # Pour usage privé, pas de publication sur pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icônes iOS
  cupertino_icons: ^1.0.8

  # Pour faire des requêtes HTTP
  http: ^0.13.6

  # Pour stocker le token JWT localement et de manière sécurisée
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
